# Simple Azure pipeline to read source from GitHub

# Currently disabled
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'AZD-EST-SND1'
  logicAppName: 'LOGICAPPSTDDEPLOY01'
  resourceGroupName: 'SNDESTLOGICAPPS-RG'

steps:
  - task: AzureCLI@2
    displayName: Azure CLI
    inputs:
      azureSubscription: '$(azureSubscription)''
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az account show
        az resource list --resource-group SNDESTLOGICAPPS-RG

  - task: AzureAppServiceSettings@1
    displayName: Azure App Service Settings
    inputs:
      azureSubscription: '$(azureSubscription)'
      appName: '$(logicAppName)'
      resourceGroupName: '$(resourceGroupName)'
      # Add the app settings for the connections 
      appSettings: |
        [
          {
            "name": "serviceBus_connectionString",
            "value": "test",
            "slotSetting": false
            },
            {
            "name": "azureFunctionOperation_functionAppKey",
            "value": "test",
            "slotSetting": false
            },
            {
            "name": "azureFunctionOperation_functionResourceURI",
            "value": "test",
            "slotSetting": false
            },
            {
            "name": "azureFunctionOperation_functionTriggerURI",
            "value": "test",
            "slotSetting": false
            }
        ]
  - task: AzureFunctionApp@2
    displayName: 'Deploy logic app workflows'
    inputs:
       azureSubscription: '$(azureSubscription)'
       appType: 'functionApp'
       appName: '$(logicAppName)'
       package: 'logicapp-artifact.zip'
       deploymentMethod: 'zipDeploy'

#  - task: AzureResourceManagerTemplateDeployment@3
#    inputs:
#      deploymentScope: "Resource Group"
#      azureResourceManagerConnection: "AZD-EST-SND1"
#      subscriptionId: "d49bcc71-d9a8-400b-9385-0015251d90c5"
#      action: "Create Or Update Resource Group"
#      resourceGroupName: "SNDESTLOGICAPPS-RG"
#      location: "UK South"
#      templateLocation: "Linked artifact"
#      csmFile: "**/workflow.json"
#      deploymentMode: "Incremental"
#      deploymentName: "logic-app-1"
