# Simple Azure pipeline to read source from GitHub

# Currently disabled
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureAppServiceSettings@1
    displayName: Azure App Service Settings
    inputs:
      azureSubscription: 'AZD-EST-SND1'
      appName: 'ESTLOGICAPP-PIPELINE'
      resourceGroupName: 'SNDESTLOGICAPPS-RG'

  - task: AzureFunctionApp@1
    displayName: 'Deploy logic app workflows'
    inputs:
       azureSubscription: 'AZD-EST-SND1'
       appType: 'functionAppLinux' ## Default: functionApp 
       appName: 'ESTLOGICAPP-PIPELINE'
       package: 'logicapp-artifact.zip'
       deploymentMethod: 'zipDeploy'

#  - task: AzureResourceManagerTemplateDeployment@3
#    inputs:
#      deploymentScope: "Resource Group"
#      azureResourceManagerConnection: "AZD-EST-SND1"
#      subscriptionId: "d49bcc71-d9a8-400b-9385-0015251d90c5"
#      action: "Create Or Update Resource Group"
#      resourceGroupName: "SNDESTLOGICAPPS-RG"
#      location: "UK South"
#      templateLocation: "Linked artifact"
#      csmFile: "src/template.json"
#      deploymentMode: "Incremental"
#      deploymentName: "logic-app-1"
