# Simple Azure pipeline to read source from GitHub

trigger:
- azure-pipelines-src-in-github

pool:
  vmImage: 'windows-latest'

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: "AZD-EST-SND1"
      subscriptionId: "d49bcc71-d9a8-400b-9385-0015251d90c5"
      action: "Create Or Update Resource Group"
      resourceGroupName: "SNDESTLOGICAPPS-RG"
      location: "UK South"
      templateLocation: "Linked artifact"
      csmFile: "src/template.json"
      deploymentMode: "Incremental"
      deploymentName: "logic-app-1"
