# Simple Azure pipeline to deploy a Logic App (Consumption) with source in GitHub

trigger:
  - feature/consumption-deploy

pool:
  vmImage: 'windows-latest'

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: "AZD-EST-SND1"
      subscriptionId: "d49bcc71-d9a8-400b-9385-0015251d90c5"
      action: "Create Or Update Resource Group"
      resourceGroupName: "SNDESTLOGICAPPS-RG"
      location: "UK South"
      templateLocation: "URL of the file"
      csmFileLink: "https://raw.githubusercontent.com/DEFRA/ffc-payment-statement-integrations/main/src/template.json"
      deploymentMode: "Incremental"
      deploymentName: "logic-app-1"
