# Azure pipeline to build a Function App with source in GitHub
# The Function App is used by the Logic App workflows to send customised emails via GovNotify.

# Trigger is manual currently
trigger: none

variables:
  - template: variables/pipeline-vars-common.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output project_func_app_output'
    projects: 'AzureFunctionGovNotify/AzureFunctionGovNotify.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false

- bash: |
    cp -r AzureFunctionGovNotify/azure-pipelines $(System.DefaultWorkingDirectory)/project_func_app_output
  displayName: 'Copy env vars and templates into artefact'

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/project_func_app_output"
    includeRootFolder: false
    archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"

- task: PublishPipelineArtifact@1
  displayName: 'Publish project zip artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifact: $(functionAppArtifactName)
    publishLocation: 'pipeline'
