# IaC Logic App resources deployment template

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: runId
  type: string

jobs:
- deployment: deploy_funcapp_resources
  displayName: Deploy Function App Resources
  pool:
    vmImage: ubuntu-latest
  environment: ${{ parameters.environment }}
  variables:
    deploymentMode: 'Incremental'
    artifactPath: '$(Pipeline.Workspace)/ci-func-app-pipeline/$(functionAppArtifactName)'
  strategy:
    runOnce:
      deploy:
        steps:
        - bash: |
            unzip -q '${{ variables.artifactPath}}/${{ parameters.runID }}.zip' -d ./unpacked
          displayName: Unzip artifact

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Function App for emails'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: './unpacked/azure-pipelines/templates/functionapp-template.json'
            overrideParameters:
              -functionAppName $(functionAppName)
              -location $(resourceGroupLocation)
              -appInsightsName $(appInsightsName)
              -resourceGroupName $(resourceGroupName)
              -storageAccountName $(functionAppStorageName)
              -hostingPlanName $(functionAppServicePlanName)
              -skuName "Y1"
              -skuTier "Dynamic"
            deploymentMode: $(deploymentMode)

        - task: AzureCLI@2
          displayName: 'Restrict access to network and whitelist Palo Alto IPs'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az resource update --name $(functionAppName) --resource-group  $(resourceGroupName) --resource-type "Microsoft.Web/sites" --set properties.siteConfig.ipSecurityRestrictionsDefaultAction=Deny
              az resource update --name $(functionAppName) --resource-group  $(resourceGroupName) --resource-type "Microsoft.Web/sites" --set properties.siteConfig.scmIpSecurityRestrictionsDefaultAction=Deny
              whitelist="$(allowedIps)"
              i=0
              for ip in ${whitelist//,/ }
              do
                  i=$(( i + 1 ))
                  az webapp config access-restriction add --name $(functionAppName) --resource-group $(resourceGroupName) --rule-name "PaloAlto IP whitelist $i" --action Allow --ip-address "$ip" --priority 100
              done
            addSpnToEnvironment: true
            useGlobalConfig: true
