#!/bin/bash
set -eu
IFS=$'\n\t'

# Creating a build manifest to pass variables to later steps in the pipeline
ENV_SHORT_NAME="test"

AZURE_SUBSCRIPTION_ID="d49bcc71-d9a8-400b-9385-0015251d90c5"
LOGIC_APP_NAME="la-$PROJECT_NAME-$ENV_SHORT_NAME"
RESOURCE_GROUP_LOCATION="uksouth"
RESOURCE_GROUP_NAME="ESTLOGICAPPS-RG2-$ENV_SHORT_NAME"
APP_SERVICE_PLAN_NAME="asp-$PROJECT_NAME-$ENV_SHORT_NAME"
# MUST BE LOWERCASE. No spaces or hyphens allowed
STORAGE_NAME="sa$PROJECT_NAME$ENV_SHORT_NAME"

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_SHORT_REVISION=$(git rev-parse --short --abbrev-commit HEAD)

# Copy to environment vars
echo "BUILD_GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
echo "BUILD_GIT_SHORT_REVISION=$GIT_SHORT_REVISION" >> $GITHUB_ENV
echo "ENV_SHORT_NAME=$ENV_SHORT_NAME" >> $GITHUB_ENV
echo "LOGIC_APP_NAME=$LOGIC_APP_NAME" >> $GITHUB_ENV
echo "AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID" >> $GITHUB_ENV
echo "RESOURCE_GROUP_LOCATION=$RESOURCE_GROUP_LOCATION" >> $GITHUB_ENV
echo "RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV
echo "APP_SERVICE_PLAN_NAME=$APP_SERVICE_PLAN_NAME" >> $GITHUB_ENV
echo "STORAGE_NAME=$STORAGE_NAME" >> $GITHUB_ENV
