# IaC variables

variables:

  # MUST BE UPPERCASE
  envShortName: 'TST'

  resourcePrefix: '$(envShortName)$(projectNameUpper)$(functionCode)'
  
  logicAppName: '$(resourcePrefix)LA1402'
  
  resourceGroupLocation: 'uksouth'
  resourceGroupName: '$(resourcePrefix)RG1401'
  
  serviceConnection: 'AZR-RLE-TST1'

  keyVaultName: '$(resourcePrefix)KV1401'

  appServicePlanName: '$(resourcePrefix)ASP1401'

   # Gets converted to lowercase later in the pipeline. No spaces or hyphens allowed
  storageName: '$(resourcePrefix)ST1402'

  appInsightsName: '$(resourcePrefix)AIS1402'

  dashboardName: '$(resourcePrefix)DSH1402'
  dashboardDisplayName: '$(logicAppName) dashboard'

  # User-assigned Managed Identity - used to access Key Vault (permissions for this can be pre-assigned before this IaC is run)
  userManagedIdentityName: '$(resourcePrefix)UAMID1401'

  # VNET integration is required for Private Endpoint blob storage
  subnetResourceId: '/resourceGroups/TSTRLENETRG1401/providers/Microsoft.Network/virtualNetworks/TSTRLENETVN1401/subnets/TSTRLENETSU1402'
  # Subnet resource ID excluding '/subscriptions/<subscriptionId>', for example: /resourceGroups/<RGname>/providers/Microsoft.Network/virtualNetworks/<VnetName>/subnets/subnetName>
  dnsServer: '10.178.0.4'
  dnsAltServer: '10.178.0.5'

  # Connector details
  # Although MID details are specified, the tenantId should be the one where the service bus exists and, if this
  # is cross-tenant, will be different to the tenant that the Logic App sits in.

  # The following are in KeyVault secrets
  # - serviceBusUserManagedIdentityTenantId - may be in a different tenant to the Logic App
  # - serviceBusUserManagedIdentityObjectId

  servicebusConnectionNameSP: 'serviceBus'
  servicebusNamespaceSP: 'TSTFFCINFSB1001.servicebus.windows.net'
  
  # Details for Azure Alerting when workflow catastrophic fails
  # Normal error alert emails use an app setting 'ErrorEmailToAddresses' CSV list of emails to send to targets
  actionGroupName: '$(resourcePrefix)AG1401'
  scheduledQueryRuleName: '$(resourcePrefix)AIAR1401'
  alertingEmailAddress: 'jeremy.barnsley@defra.gov.uk'