# IaC variables

variables:

  envShortName: 'test'
  envShortNameUpper: 'TEST'

  logicAppName: '$(envShortNameUpper)$(projectNameUpper)'
  logicAppNameLower: '$(envShortName)$(projectNameLower)'
  
  resourceGroupLocation: 'uksouth'
  resourceGroupName: 'TSTRLEINFRG1401'

  #
  # CHANGE when TST is set up
  #
  serviceConnection: 'AZD-RLE-DEV1'

  keyVaultName: 'TSTRLEINFKV1401'

  appServicePlanName: 'ASP-$(logicAppName)'

   # MUST BE LOWERCASE. No spaces or hyphens allowed
  storageName: 'sa$(envShortName)$(projectNameLower)'

  appInsightsName: '$(logicAppName)AI'

  dashboardName: '$(logicAppName)DH'
  dashboardDisplayName: '$(logicAppName) dashboard'

  # Full url is specified here as opposed to just the MI name.
  # User-assigned Managed Identity to be attributed to the Logic App.
  # Resource Group is supplied in case it is in a different resource group to the Logic App.
  userManagedIdentityName: 'MILOGICAPPSTST'
  userManagedIdentityResourceGroupName: 'TSTRLEINFRG1401'

  # Connector details
  # Although MID details are specified, the tenantId should be the one where the service bus exists and, if this
  # is cross-tenant, will be different to the tenant that the Logic App sits in.

  # The following are in KeyVault secrets
  # - serviceBusUserManagedIdentityTenantId
  # - serviceBusUserManagedIdentityObjectId

  servicebusConnectionNameSP: 'serviceBus'
  servicebusNamespaceSP: 'SNDFFCINFSB1001.servicebus.windows.net'

  servicebusConnectionNameAPI: 'pay-servicebus-api'
  servicebusNamespaceAPI: 'SNDFFCINFSB1001.servicebus.windows.net'
