# IaC variables

variables:

  envShortName: 'test'

  logicAppName: 'la-$(projectName)-$(envShortName)'
 
  resourceGroupLocation: 'uksouth'
  resourceGroupName: 'ESTLOGICAPPS-RG2-$(envShortName)'

  serviceConnection: 'AZD-EST-SND1'

  appServicePlanName: 'asp-$(projectName)-$(envShortName)'

   # MUST BE LOWERCASE. No spaces or hyphens allowed
  storageName: 'sa$(projectName)$(envShortName)'

  appInsightsName: 'la-$(projectName)-$(envShortName)'

  # Full url is specified here as opposed to just the MI name.
  # This is because the MI may exist in a different resource group than the Logic App and so
  # the normal resource lookup in the template will fail.
  userManagedIdentityUrl: '/subscriptions/d49bcc71-d9a8-400b-9385-0015251d90c5/resourcegroups/SNDESTLOGICAPPS-RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/MILOGICAPPSDEV'