# IaC variables

variables:

  # MUST BE UPPERCASE
  envShortName: 'DEV'

  resourcePrefix: '$(envShortName)$(projectNameUpper)$(functionCode)'

  logicAppName: '$(resourcePrefix)LA1402'
  
  resourceGroupLocation: 'uksouth'
  resourceGroupName: '$(resourcePrefix)RG1401'
  
  serviceConnection: 'AZD-RLE-DEV1'

  appServicePlanName: '$(resourcePrefix)ASP1401'

   # Gets converted to lowercase later in the pipeline. No spaces or hyphens allowed
  storageName: '$(resourcePrefix)ST1402'
  fileShareName: '$(resourcePrefix)ST1402fs'

  appInsightsName: '$(resourcePrefix)AIS1402'

  dashboardName: '$(resourcePrefix)DSH1402'
  dashboardDisplayName: '$(logicAppName) dashboard'

  # User-assigned Managed Identity - used to access Key Vault (permissions for this can be pre-assigned before this IaC is run)
  userManagedIdentityName: '$(resourcePrefix)UAMID1401'

  # VNET integration is required for Private Endpoint blob storage
  subnetResourceId: '/resourceGroups/DEVRLENETRG1401/providers/Microsoft.Network/virtualNetworks/DEVRLENETVN1401/subnets/DEVRLENETSU1402'
  # Subnet resource ID excluding '/subscriptions/<subscriptionId>', for example: /resourceGroups/<RGname>/providers/Microsoft.Network/virtualNetworks/<VnetName>/subnets/subnetName>
  dnsServer: '10.178.0.4'
  dnsAltServer: '10.178.0.5'

  # Connector details for external Service Bus
  servicebusConnectionNameSP: 'serviceBus'
  servicebusNamespaceSP: 'SNDFFCINFSB1001.servicebus.windows.net'

  # Details for Azure Alerting when workflow catastrophic fails
  actionGroupName: '$(resourcePrefix)AG1401'
  scheduledQueryRuleName: '$(resourcePrefix)AIAR1401'
  alertingEmailAddress: 'jeremy.barnsley@defra.gov.uk'