# IaC variables

variables:

  # MUST BE UPPERCASE
  envShortName: 'TST'

  resourcePrefix: '$(envShortName)$(projectNameUpper)$(functionCode)'
  
  logicAppName: '$(resourcePrefix)LA1402'
  
  resourceGroupLocation: 'uksouth'
  resourceGroupName: '$(resourcePrefix)RG1401'
  
  serviceConnection: 'AZR-RLE-TST1'

  appServicePlanName: '$(resourcePrefix)ASP1401'

   # Gets converted to lowercase later in the pipeline. No spaces or hyphens allowed
  storageName: '$(resourcePrefix)ST1402'
  fileShareName: '$(resourcePrefix)ST1402fs'

  appInsightsName: '$(resourcePrefix)AIS1402'

  dashboardName: '$(resourcePrefix)DSH1402'
  dashboardDisplayName: '$(logicAppName) dashboard'

  # User-assigned Managed Identity - used to access Key Vault (permissions for this can be pre-assigned before this IaC is run)
  userManagedIdentityName: '$(resourcePrefix)UAMID1401'

  # VNET integration is required for Private Endpoint blob storage
  subnetResourceId: '/resourceGroups/TSTRLENETRG1401/providers/Microsoft.Network/virtualNetworks/TSTRLENETVN1401/subnets/TSTRLENETSU1402'
  # Subnet resource ID excluding '/subscriptions/<subscriptionId>', for example: /resourceGroups/<RGname>/providers/Microsoft.Network/virtualNetworks/<VnetName>/subnets/subnetName>
  dnsServer: '10.178.0.4'
  dnsAltServer: '10.178.0.5'

    # Connector details for external Service Bus
  # These details refer to the tenant and resource group where the service bus identity exists and, if this
  # is cross-tenant, will be different to the tenant that the Logic App sits in.
  servicebusConnectionNameSP: 'serviceBus'
  servicebusNamespaceSP: 'SNDFFCINFSB1001.servicebus.windows.net'
  externalServiceBusManagedIdentityName: 'DEVRLEINFMI1401'
  externalServiceBusResourceGroupName: 'DEVRLEINFRG1401'
  externalServiceBusSubscriptionName: 'AZD-RLE-DEV1'
  
  # Details for Azure Alerting when workflow catastrophic fails
  actionGroupName: '$(resourcePrefix)AG1402'
  scheduledQueryRuleName: '$(resourcePrefix)AIAR1402'
  alertingEmailAddress: 'jeremy.barnsley@defra.gov.uk'