# IaC variables

variables:

  envShortName: 'test'

  logicAppName: 'la-$(projectName)-$(envShortName)'
 
  resourceGroupLocation: 'uksouth'
  resourceGroupName: 'TSTRLEINFRG1401'

  serviceConnection: 'AZD-RLE-TST1'

  keyVaultName: 'TSTRLEINFKV1401'

  appServicePlanName: 'asp-$(projectName)-$(envShortName)'

   # MUST BE LOWERCASE. No spaces or hyphens allowed
  storageName: 'sa$(projectName)$(envShortName)'

  appInsightsName: 'la-$(projectName)-$(envShortName)'

  dashboardName: 'dh-$(projectName)-$(envShortName)'
  dashboardDisplayName: '$(projectName)-$(envShortName) dashboard'

  # Full url is specified here as opposed to just the MI name.
  # User-assigned Managed Identity to be attributed to the Logic App.
  # Resource Group is supplied in case it is in a different resource group to the Logic App.
  userManagedIdentityName: 'MILOGICAPPSTST'
  userManagedIdentityResourceGroupName: 'TSTRLEINFRG1401'

  # Connector details
  # Although MID details are specified, the tenantId should be the one where the service bus exists and, if this
  # is cross-tenant, will be different to the tenant that the Logic App sits in.

  # The following are in KeyVault secrets
  # - serviceBusUserManagedIdentityTenantId
  # - serviceBusUserManagedIdentityObjectId

  servicebusConnectionNameSP: 'serviceBus'
  servicebusNamespaceSP: 'SNDFFCINFSB1001.servicebus.windows.net'

  servicebusConnectionNameAPI: 'pay-servicebus-api'
  servicebusNamespaceAPI: 'SNDFFCINFSB1001.servicebus.windows.net'
