# IaC variables

variables:

  envShortName: 'test'

  logicAppName: 'la-$(projectName)-$(envShortName)'
 
  resourceGroupLocation: 'uksouth'
  resourceGroupName: 'ESTLOGICAPPS-RG2-$(envShortName)'

  serviceConnection: 'AZD-EST-SND1'

  appServicePlanName: 'asp-$(projectName)-$(envShortName)'

   # MUST BE LOWERCASE. No spaces or hyphens allowed
  storageName: 'sa$(projectName)$(envShortName)'

  appInsightsName: 'la-$(projectName)-$(envShortName)'

  dashboardName: 'dh-$(projectName)-$(envShortName)'
  dashboardDisplayName: '$(projectName)-$(envShortName) dashboard'

  # Full url is specified here as opposed to just the MI name.
  # User-assigned Managed Identity to be attributed to the Logic App.
  # Resource Group is supplied in case it is in a different resource group to the Logic App.
  userManagedIdentityName: 'MILOGICAPPSDEV'
  userManagedIdentityResourceGroupName: 'SNDESTLOGICAPPS-RG'

  # Connector details
  # Although MID details are specified, the tenantId should be the one where the service bus exists and, if this
  # is cross-tenant, will be different to the tenant that the Logic App sits in.
  userManagedIdentityTenantId: 'c9d74090-b4e6-4b04-981d-e6757a160812'
  userManagedIdentityObjectId: 'd1fd46e8-9d18-47d4-afab-b63513cb5098'

  servicebusConnectionNameSP: 'serviceBus'
  servicebusNamespaceSP: 'SNDFFCINFSB1001.servicebus.windows.net'

  servicebusConnectionNameAPI: 'pay-servicebus-api'
  servicebusNamespaceAPI: 'SNDFFCINFSB1001.servicebus.windows.net'
