# IaC variables

variables:

  # MUST BE UPPERCASE
  envShortName: 'DEV'

  resourcePrefix: '$(envShortName)$(projectNameUpper)$(functionCode)'

  logicAppName: '$(resourcePrefix)LA1402'
  
  resourceGroupLocation: 'uksouth'
  resourceGroupName: '$(resourcePrefix)RG1401'
  
  serviceConnection: 'AZD-RLE-DEV1'

  keyVaultName: '$(resourcePrefix)KV1401'

  appServicePlanName: '$(resourcePrefix)ASP1401'

   # Gets converted to lowercase later in the pipeline. No spaces or hyphens allowed
  storageName: '$(resourcePrefix)ST1402'

  appInsightsName: '$(resourcePrefix)AIS1402'

  dashboardName: '$(resourcePrefix)DSH1402'
  dashboardDisplayName: '$(logicAppName) dashboard'

  # Full url is specified here as opposed to just the MI name.
  # User-assigned Managed Identity to be attributed to the Logic App.
  # Resource Group is supplied in case it is in a different resource group to the Logic App.
  userManagedIdentityName: '$(resourcePrefix)MI1401'
  userManagedIdentityResourceGroupName: '$(resourceGroupName)'

  # Connector details
  # Although MID details are specified, the tenantId should be the one where the service bus exists and, if this
  # is cross-tenant, will be different to the tenant that the Logic App sits in.
  
  servicebusConnectionNameSP: 'serviceBus'
  servicebusNamespaceSP: 'SNDFFCINFSB1001.servicebus.windows.net'

  # The following are in KeyVault secrets
  # - serviceBusUserManagedIdentityTenantId
  # - serviceBusUserManagedIdentityObjectId

  servicebusConnectionNameAPI: 'pay-servicebus-api'
  servicebusNamespaceAPI: 'SNDFFCINFSB1001.servicebus.windows.net'
  