# IaC variables

variables:

  envShortName: 'dev'
  envShortNameUpper: 'DEV'

  logicAppName: '$(envShortNameUpper)$(projectNameUpper)'
  
  resourceGroupLocation: 'uksouth'
  resourceGroupName: 'DEVRLEINFRG1401'
  
  serviceConnection: 'AZD-RLE-DEV1'

  keyVaultName: 'DEVRLEINFKV1401'

  appServicePlanName: 'ASP-$(logicAppName)'

   # MUST BE LOWERCASE. No spaces or hyphens allowed
  storageName: '$(envShortName)$(projectNameLower)sa'

  appInsightsName: '$(logicAppName)AI'

  dashboardName: '$(logicAppName)DH'
  dashboardDisplayName: '$(logicAppName) dashboard'

  # Full url is specified here as opposed to just the MI name.
  # User-assigned Managed Identity to be attributed to the Logic App.
  # Resource Group is supplied in case it is in a different resource group to the Logic App.
  userManagedIdentityName: 'MILOGICAPPSDEV'
  userManagedIdentityResourceGroupName: '$(resourceGroupName)'

  # Connector details
  # Although MID details are specified, the tenantId should be the one where the service bus exists and, if this
  # is cross-tenant, will be different to the tenant that the Logic App sits in.
  
  servicebusConnectionNameSP: 'serviceBus'
  servicebusNamespaceSP: 'SNDFFCINFSB1001.servicebus.windows.net'

  # The following are in KeyVault secrets
  # - serviceBusUserManagedIdentityTenantId
  # - serviceBusUserManagedIdentityObjectId

  #servicebusConnectionNameAPI: 'pay-servicebus-api'
  #servicebusNamespaceAPI: 'SNDFFCINFSB1001.servicebus.windows.net'
  