# GitHub Action workflow (pipeline) for deployment of underlying workflows
name: Deploy Logic App workflows (Standard)

#On merge of PR into main - assuming main is a protected branch
on:
 push:
   branches:
#     - main
     - github-split-env

jobs:
  deploy-dev:
    uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/cd-sub-workflow.yml@github-split-env
    with:
      env-short-name: 'dev'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
  
  deploy-test:
    uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/cd-sub-workflow.yml@github-split-env
    with:
      env-short-name: 'test'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
    