# GitHub Action workflow (pipeline) for deployment of underlying workflows
name: Deploy Logic App workflows (Standard)

# Currently only manual trigger
on:
  workflow_dispatch
# push:
#   branches:
#     - main

jobs:
  deploy-dev:
    uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/cd-sub-workflow.yml@github-split-env
    with:
      env-short-name: 'dev'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
  
  deploy-test:
    uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/cd-sub-workflow.yml@github-split-env
    with:
      env-short-name: 'test'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
    