# GitHub Actions workflow to build and test a Logic App (Standard)

name: Build and test Logic App

#On merge of PR into main - assuming main is a protected branch
on:
 push:
#   branches:
#     - main

env:
  project-name: 'PaymentStatementIntegrations.Tests/PaymentStatementIntegrations.Tests.csproj'

jobs:
  validate-and-deploy:
   runs-on: ubuntu-latest
   
   steps:

    #Check out files
    - name: Check out files
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore ${{ env.project-name }}

    - name: Build Tests
      run: dotnet build ${{ env.project-name }} --no-restore

    - name: set up node
      uses: actions/setup-node@v1
      with:
          node-version: '14.x'

    - name: Install and run azurite
      run: |
        npm install -g azurite
        mkdir azurite
        azurite --silent --location azurite --debug azurite\debug.log &

    - name: Run Tests
      run: dotnet test ${{ env.project-name }} --no-restore --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true      
