# GitHub Action workflow for single environment deployment of Logic App top-level resources
name: "_sub single env - deploy Logic App resources"
# excluding underlying workflows

on:
  workflow_call:
    inputs:
      env-short-name:
        required: true
        type: string
    secrets:
      azure-credentials:
        required: true

jobs:
  deploy:
   runs-on: ubuntu-latest
   environment:
     name: ${{ inputs.env-short-name }}

   steps:

    # Check out files
    - name: Check out files
      uses: actions/checkout@v3

    # Download artifact
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci-workflow.yml
        workflow_conclusion: success
        path: ./output/

    # Log on to azure using service pricipal
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.azure-credentials }}
  
    # Set up common variables
    - name: Set up common variables
      run: |
        ./cd/setup_vars_common.sh

    # Set up environment-specific variables
    # This has to be a separate step from common vars in order for this step to use common vars
    - name: Set up env-specific variables
      run: |
        ./cd/setup_vars_${{ inputs.env-short-name }}.sh
 
    - name: Unzip artifact
      run: |
        ZIP_PATH_AND_FILE=`ls ./output/${{ env.ARTIFACT_NAME }}/*.zip`
        unzip -q $ZIP_PATH_AND_FILE -d ./unpacked
        echo "ZIP_PATH_AND_FILE=$ZIP_PATH_AND_FILE" >> $GITHUB_ENV
  
# Workflow doesn't have perms to create resource groups currently
#    - name: Create resource group (if not exists)
#      uses: Azure/CLI@v1
#      with:
#        inlineScript: |
#          #!/bin/bash
#          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
#          echo "Azure resource group created or already exists"

    # Deploy the Logic App resources
    - name: Deploy Logic App resources
      uses: Azure/arm-deploy@v1.0.1
      id: ladeploy
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        scope: resourcegroup  
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName:  ${{ env.RESOURCE_GROUP_NAME }}
        template: ./unpacked/templates/logicapp-template.json  # Set this to the location of your template file
        parameters: appServicePlanName=${{env.APP_SERVICE_PLAN_NAME}} environmentName=${{ env.ENV_SHORT_NAME}} location=${{ env.RESOURCE_GROUP_LOCATION }} logicAppName=${{ env.LOGIC_APP_NAME }} projectName=${{ env.PROJECT_NAME }} storageName=${{ env.STORAGE_NAME }}
        deploymentMode: Incremental
   
    # Deployment of template    
    - name: Deploy Connector Resources 
      id: conndeploy
      uses: Azure/arm-deploy@v1.0.1
      with:
        scope: resourcegroup  
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./unpacked/templates/connectors-template.json  # Set this to the location of your template file
        parameters: logicAppSystemAssignedIdentityTenantId=${{ steps.ladeploy.outputs.logicAppSystemAssignedIdentityTenantId }} logicAppSystemAssignedIdentityObjectId=${{ steps.ladeploy.outputs.logicAppSystemAssignedIdentityObjectId }}  location=${{ env.RESOURCE_GROUP_LOCATION }} connections_azureblob_name=${{ env.BLOB_CONNECTION_NAME }}
        deploymentMode: Incremental

    - name: Update Logic App Connections 
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp config appsettings set --name ${{ steps.ladeploy.outputs.LAname }} --resource-group  ${{ env.RESOURCE_GROUP_NAME }} --settings "BLOB_CONNECTION_RUNTIMEURL=${{ steps.conndeploy.outputs.blobendpointurl }}"
          az functionapp config appsettings set --name ${{ steps.ladeploy.outputs.LAname }} --resource-group  ${{ env.RESOURCE_GROUP_NAME }} --settings "WORKFLOWS_RESOURCE_GROUP_NAME=${{ env.RESOURCE_GROUP_NAME }}"

    - name: Logout from Azure
      run: |
        az logout