name: Deploy Logic App (Standard) excluding underlying workflows

#On merge of PR into main - assuming main is a protected branch
on:
 push:
   branches:
#     - main
     - github-pipelines

jobs:
  deploy-dev:
   runs-on: ubuntu-latest
   environment:
     name: dev

   steps:

    #Check out files
    - name: Check out files
      uses: actions/checkout@v3

    #Use the azure provided action to log on to azure using service pricipal
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    
    # Deploy the Logic App resources
    - name: Deploy Logic App resources
      uses: Azure/arm-deploy@v1.0.1
      id: ladeploy
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        scope: resourcegroup  
        subscriptionId: ${{ vars.AZURE_SUBCRIPTION }}
        resourceGroupName:  ${{ vars.RG_NAME }}
        template: azure-pipelines/templates/logicapp-template.json  # Set this to the location of your template file
        deploymentMode: Incremental
   
    # Deployment of template    
    - name: Deploy Connector Resources 
      id: conndeploy
      uses: Azure/arm-deploy@v1.0.1
      with:
        scope: resourcegroup  
        subscriptionId: ${{ vars.AZURE_SUBCRIPTION }}
        resourceGroupName: ${{ vars.RG_NAME }}
        template: ARM/connectors-template.json  # Set this to the location of your template file
        parameters: ARM/connectors-parameters.json logicAppSystemAssignedIdentityTenantId=${{ steps.ladeploy.outputs.logicAppSystemAssignedIdentityTenantId }} logicAppSystemAssignedIdentityObjectId=${{ steps.ladeploy.outputs.logicAppSystemAssignedIdentityObjectId }}
        deploymentMode: Incremental

    - name: Update Logic App Connections 
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp config appsettings set --name ${{ steps.ladeploy.outputs.LAname }} --resource-group  ${{ vars.RG_NAME }} --settings "BLOB_CONNECTION_RUNTIMEURL=${{ steps.conndeploy.outputs.blobendpointurl }}"
          az functionapp config appsettings set --name ${{ steps.ladeploy.outputs.LAname }} --resource-group  ${{ vars.RG_NAME }} --settings "WORKFLOWS_RESOURCE_GROUP_NAME=${{ vars.RG_NAME }}"

  