# GitHub Action workflow (pipeline) for deployment of Logic App top-level resources
name: Deploy Logic App resources (Standard)
# excluding underlying workflows

#On merge of PR into main - assuming main is a protected branch
on:
 push:
   branches:
#     - main
      - github-split-env

jobs:
  deploy-dev:
   runs-on: ubuntu-latest
   environment:
     name: dev

   steps:
    - name: Deploy to dev
      uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/iac-sub-workflow.yml@github-split-env
      with:
        env-short-name: 'dev'
        
  deploy-test:
    runs-on: ubuntu-latest
    environment:
      name: test
  
    steps:
      - name: Deploy to test
        uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/iac-sub-workflow.yml@github-split-env
        with:
          env-short-name: 'test'
  