# GitHub Action workflow (pipeline) for deployment of Logic App top-level resources
name: Deploy Logic App resources (Standard)
# excluding underlying workflows

# Currently only manual trigger
on:
#  workflow_dispatch
 push:
   branches:
#     - main
     - github-fixes

jobs:
  deploy-dev:
    uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/iac-sub-workflow.yml@main
    with:
      env-short-name: dev
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          
  deploy-test:
    uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/iac-sub-workflow.yml@main
    with:
      env-short-name: test
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
