# GitHub Action workflow (pipeline) for deployment of Logic App top-level resources
name: IaC - Deploy Logic App infrastructure
# excluding underlying workflows

# Currently only manual trigger
on:
  workflow_dispatch
# push:
#   branches:
#     - main

jobs:
  deploy-dev:
    uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/iac-sub-workflow.yml@jb-dev-fix
    with:
      env-short-name: dev
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
  deploy-test:
    uses: DEFRA/ffc-payment-statement-integrations/.github/workflows/iac-sub-workflow.yml@main
    with:
      env-short-name: test
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
