# Logic App workflows deployment template

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: runId
  type: string
- name: settingsFile
  type: string

jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    variables:
      deploymentMode: 'Incremental'
      artifactPath: '$(Pipeline.Workspace)/cipipeline/$(artifactName)'
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: |
              unzip -q '${{ variables.artifactPath}}/${{ parameters.runID }}.zip' -d ./unpacked
            displayName: Unzip artifact

          - bash: |
              echo "##vso[task.setvariable variable=settingsJson]$(cat ./unpacked/${{ parameters.settingsFile }} | tr -d '\n')"
            displayName: 'Read settings for environment ${{ parameters.environment }}'

          - task: AzureAppServiceSettings@1
            displayName: Azure App Service Settings
            inputs:
              azureSubscription: ${{ parameters.serviceConnection}}
              appName: $(logicAppName)
              resourceGroupName: $(resourceGroupName)
              appSettings: $(settingsJson)

          - task: AzureFunctionApp@2
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              appType: 'functionApp'
              appName: $(logicAppName)
              package: '$(Pipeline.Workspace)/cipipeline/$(artifactName)/${{ parameters.runID }}.zip'
              deploymentMethod: 'zipDeploy'
