# Logic App workflows deployment template

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: runId
  type: string
- name: settingsFile
  type: string

jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    variables:
      deploymentMode: 'Incremental'
      artifactPath: '$(Pipeline.Workspace)/cipipeline/logicapp-artifact'
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: |
              unzip -q '${{ variables.artifactPath}}/${{ parameters.runID }}.zip'
              ls -al ${{ variables.artifactPath }}
            displayName: Unzip artifact

          - bash: |
              echo "##vso[task.setvariable variable=settingsJson]$(cat ${{ variables.artifactPath }}/${{ parameters.settingsFile }})"
            displayName: Read settings

          - bash: |
              echo "settings:$(settingsJson)"
            displayName: Confirm settings

          - task: AzureAppServiceSettings@1
            displayName: Azure App Service Settings
            inputs:
              azureSubscription: ${{ parameters.serviceConnection}}
              appName: $(logicAppName)
              resourceGroupName: $(resourceGroupName)
              appSettings: $(settingsJson)

          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              appType: 'functionApp'
              appName: $(logicAppName)
              package: '$(Pipeline.Workspace)/cipipeline/logicapp-artifact/${{ parameters.runID }}.zip'
              deploymentMethod: 'zipDeploy'
