# IaC Logic App resources deployment template

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: runId
  type: string

jobs:
- deployment: deploy_logicapp_resources
  displayName: Deploy Logic App Resources
  pool:
    vmImage: ubuntu-latest
  environment: ${{ parameters.environment }}
  variables:
    deploymentMode: 'Incremental'
    artifactPath: '$(Pipeline.Workspace)/cipipeline/$(artifactName)'
  strategy:
    runOnce:
      deploy:
        steps:
        - bash: |
            unzip -q '${{ variables.artifactPath}}/${{ parameters.runID }}.zip' -d ./unpacked
          displayName: Unzip artifact

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Logic App'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: '$(Pipeline.Workspace)/unpacked/template/logicapp-template.json'
            overrideParameters:
              -location $(resourceGroupLocation)
              -environmentName ${{ parameters.environment }}
              -projectName $(projectName)
              -logicAppName $(logicAppName)
              -appServicePlanName $(appServicePlanName)
              -storageName $(storageName)
            deploymentMode: $(deploymentMode)
            deploymentOutputs: 'LogicAppArmOutputs'

        - task: ARM Outputs@6
          displayName: 'ARM Outputs'
          inputs:
            ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
            ConnectedServiceNameARM: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            whenLastDeploymentIsFailed: 'fail'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Connectors'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: '$(Pipeline.Workspace)/unpacked/connectors-template.json'
            overrideParameters:
              -location $(resourceGroupLocation)
              -connections_azureblob_name $(blobConnectionName)
              -logicAppSystemAssignedIdentityTenantId $(logicAppSystemAssignedIdentityTenantId)
              -logicAppSystemAssignedIdentityObjectId $(logicAppSystemAssignedIdentityObjectId)
            deploymentMode: $(deploymentMode)

        - task: ARM Outputs@6
          displayName: 'ARM Outputs Connections'
          inputs:
            ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
            ConnectedServiceNameARM: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            whenLastDeploymentIsFailed: 'fail'

        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az functionapp config appsettings set --name $(LAname) --resource-group  $(resourceGroupName) --settings "BLOB_CONNECTION_RUNTIMEURL=$(blobendpointurl)"
              az functionapp config appsettings set --name $(LAname) --resource-group  $(resourceGroupName) --settings "WORKFLOWS_RESOURCE_GROUP_NAME=$(resourceGroupName)"
            addSpnToEnvironment: true
            useGlobalConfig: true