# Logic App workflows deployment template

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: runId
  type: string
- name: settingsFile
  type: string
- name: connectionsFile
  type: string
- name: keyVaultName
  type: string

jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.environment }}
    variables:
      deploymentMode: 'Incremental'
      artifactPath: '$(Pipeline.Workspace)/cipipeline/$(logicAppArtifactName)'
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: |
              unzip -q '${{ variables.artifactPath}}/${{ parameters.runID }}.zip' -d ./unpacked
            displayName: Unzip artifact

          - bash: |
              echo "##vso[task.setvariable variable=settingsJson]$(cat ./unpacked/${{ parameters.settingsFile }} | tr -d '\n')"
            displayName: 'Read settings for environment ${{ parameters.environment }}'

          - task: AzureAppServiceSettings@1
            displayName: Azure App Service Settings
            inputs:
              azureSubscription: ${{ parameters.serviceConnection}}
              appName: $(logicAppName)
              resourceGroupName: $(resourceGroupName)
              appSettings: $(settingsJson)

          - bash: |
              cd ./unpacked
              cp ${{ parameters.connectionsFile }} connections.json
              zip -r newArtifact.zip *
            displayName: 'Use environment-specific connections.json - create new artifact'

          - task: AzureFunctionApp@2
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              appType: 'functionApp'
              appName: $(logicAppName)
              package: './unpacked/newArtifact.zip'
              deploymentMethod: 'zipDeploy'

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              KeyVaultName: ${{ parameters.keyVaultName }}
              SecretsFilter: '*'
              RunAsPreJob: false

          - task: AzureCLI@2
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az resource show --name $(logicAppName) --resource-group  $(resourceGroupName) --resource-type "Microsoft.Web/sites" --query "identity" > tempId.json
                echo "##vso[task.setvariable variable=logicAppSystemAssignedIdentityObjectId]$(cat tempId.json | grep 'principalId' | tr -d ',' | awk '{ print $2; }' | tr -d '"')"
                echo "##vso[task.setvariable variable=logicAppSystemAssignedIdentityTenantId]$(cat tempId.json | grep 'tenantId' | tr -d ',' | awk '{ print $2; }' | tr -d '"')"
                rm tempId.json
              addSpnToEnvironment: true
              useGlobalConfig: true
            displayName: 'Read System-Assigned Managed Identity'

          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy Connectors'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              resourceGroupName: $(resourceGroupName)
              location: $(resourceGroupLocation)
              csmFile: './unpacked/templates/connectors-template.json'
              overrideParameters:
                -location $(resourceGroupLocation)
                -connections_servicebus_name_sp $(servicebusConnectionNameSP)
                -servicebus_connection_string_sp $(ServiceBusConnectionStringDev)
                -serviceBusUserManagedIdentityTenantId $(ServiceBusUserManagedIdentityTenantIdDev)
                -serviceBusUserManagedIdentityObjectId $(ServiceBusUserManagedIdentityObjectIdDev)
                -logicAppSystemAssignedIdentityTenantId $(logicAppSystemAssignedIdentityTenantId)
                -logicAppSystemAssignedIdentityObjectId $(logicAppSystemAssignedIdentityObjectId)
                -portal_client_id $(PortalClientId)
                -portal_client_secret $(PortalClientSecret)
                -portal_tenant_id $(PortalTenantId)
              deploymentMode: $(deploymentMode)

          - task: ARM Outputs@6
            displayName: 'ARM Outputs Connectors'
            inputs:
              ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
              ConnectedServiceNameARM: ${{ parameters.serviceConnection }}
              resourceGroupName: $(resourceGroupName)
              whenLastDeploymentIsFailed: 'fail'

          - task: AzureCLI@2
            displayName: 'App Settings for Connectors'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az functionapp config appsettings set --name $(logicAppName) --resource-group  $(resourceGroupName) --settings \
                "SERVICEBUS_CONNECTION_SP_RUNTIMEURL=$(servicebusendpointurlsp)"
              addSpnToEnvironment: true
              useGlobalConfig: true
