# IaC Logic App resources deployment template

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: runId
  type: string

jobs:
- deployment: deploy_logicapp_resources
  displayName: Deploy Logic App Resources
  pool:
    vmImage: ubuntu-latest
  environment: ${{ parameters.environment }}
  variables:
    deploymentMode: 'Incremental'
    artifactPath: '$(Pipeline.Workspace)/cipipeline/$(artifactName)'
  strategy:
    runOnce:
      deploy:
        steps:
        - bash: |
            unzip -q '${{ variables.artifactPath}}/${{ parameters.runID }}.zip' -d ./unpacked
          displayName: Unzip artifact

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Logic App'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: './unpacked/templates/logicapp-template.json'
            overrideParameters:
              -location $(resourceGroupLocation)
              -environmentName ${{ parameters.environment }}
              -projectName $(projectNameUpper)
              -logicAppName $(logicAppName)
              -appServicePlanName $(appServicePlanName)
              -storageName $(storageName)
              -appInsightsName $(appInsightsName)
              -userManagedIdentityName $(userManagedIdentityName)
              -userManagedIdentityResourceGroupName $(userManagedIdentityResourceGroupName)
              -subnetResourceId $(subnetResourceId)
              -dnsServer $(dnsServer)
              -dnsAltServer $(dnsAltServer)
            deploymentMode: $(deploymentMode)
            deploymentOutputs: 'LogicAppArmOutputs'

        - task: ARM Outputs@6
          displayName: 'ARM Outputs'
          inputs:
            ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
            ConnectedServiceNameARM: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            whenLastDeploymentIsFailed: 'fail'

        # These settings cannot be applied as part of the Logic App template (for some reason) so have to be applied afterwards here
        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az functionapp config appsettings set --name $(LAname) --resource-group  $(resourceGroupName) --settings "WORKFLOWS_RESOURCE_GROUP_NAME=$(resourceGroupName)"
              az functionapp config appsettings set --name $(LAname) --resource-group  $(resourceGroupName) --settings "WEBSITE_LOAD_ROOT_CERTIFICATES=$(trustedRootThumbprints)"
            addSpnToEnvironment: true
            useGlobalConfig: true

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Dashboard'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
            csmFile: './unpacked/templates/dashboard-template.json'
            overrideParameters:
              -location $(resourceGroupLocation)
              -logicAppName $(logicAppName)
              -appInsightsName $(appInsightsName)
              -logicAppResourceGroup $(resourceGroupName)
              -dashboardName $(dashboardName)
              -dashboardDisplayName "$(dashboardDisplayName)"
            deploymentMode: $(deploymentMode)
