# Azure pipeline to deploy a Logic App (Standard) to one or more environments
# This pipeline deploys the workflows which sit under the Logic App structure.
# The Logic App structure (including service plan, storage account and connections)
# is deployed separately using the iac-pipeline.yml pipeline.

trigger: none

pr: none

resources:
  pipelines:
  - pipeline: cipipeline
    source: payment-statement-integrations-ci
    trigger:
      branches:
      - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars-dev.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: dev
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            displayName: Azure App Service Settings
            inputs:
              azureSubscription: '$(serviceConnection)'
              appName: '$(logicAppName)'
              resourceGroupName: '$(resourceGroupName)'
              # App settings for the connections 
              appSettings: |
                [
                  {
                    "name": "serviceBusConnectionString",
                    "value": "$(serviceBusConnectionString-dev)",
                    "slotSetting": false
                    },
                    {
                    "name": "commonDataServiceWrite",
                    "value": "$(commonDataServiceWrite-dev)",
                    "slotSetting": false
                    },
                    {
                    "name": "PdfServiceUrl",
                    "value": "$(PdfServiceUrl-dev)",
                    "slotSetting": false
                    },
                    {
                    "name": "AuthTokenValidationUrl",
                    "value": "test",
                    "slotSetting": false
                    }
                ]

          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: '$(serviceConnection)'
              appType: 'functionApp'
              appName: '$(logicAppName)'
              package: '$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip'
              deploymentMethod: 'zipDeploy'