# Azure pipeline to deploy a Logic App (Standard) to one or more environments
# This pipeline deploys the workflows which sit under the Logic App structure.
# The Logic App structure (including service plan, storage account and connections)
# is deployed separately using the iac-pipeline.yml pipeline.

trigger: none

pr: none

variables:
- template: variables/pipeline-vars-common.yml

resources:
  pipelines:
  - pipeline: cipipeline
    source: payment-statement-integrations-ci
    trigger:
      branches:
      - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars-dev.yml
  jobs:
  - template: templates/template-cd-logicapp.yml
    parameters:
      environment: ${{ variables.envShortName }}
      serviceConnection: ${{ variables.serviceConnection }}
      runId: $(resources.pipeline.cipipeline.runID)