trigger: none

pr: none

variables:
- name: azureSubscription
  value: AZD-EST-SND1
- name: logicAppName
  value: LOGICAPPSTANDARD02
- name: logicAppCIArtifactName
  value: logicapp-artifact

resources:
  pipelines:
  - pipeline: cipipeline
    source: payment-statement-integrations-ci
    trigger:
      branches:
      - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: dev
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            displayName: Azure App Service Settings
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(logicAppName)-dev'
              resourceGroupName: '$(resourceGroupName)'
              # App settings for the connections 
              appSettings: |
                [
                  {
                    "name": "serviceBusConnectionString",
                    "value": "$(serviceBusConnectionString-dev)",
                    "slotSetting": false
                    },
                    {
                    "name": "commonDataServiceWrite",
                    "value": "$(commonDataServiceWrite-dev)",
                    "slotSetting": false
                    },
                    {
                    "name": "PdfServiceUrl",
                    "value": "$(PdfServiceUrl-dev)",
                    "slotSetting": false
                    },
                    {
                    "name": "AuthTokenValidationUrl",
                    "value": "test",
                    "slotSetting": false
                    }
                ]

          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'functionApp'
              appName: '$(logicAppName)-dev'
              package: '$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip'
              deploymentMethod: 'zipDeploy'