trigger: none

pr: none

variables:
- name: artifactName
  value: deploy_artifacts
- name: devEnvironment
  value: dev
- name: testEnvironment
  value: test

stages:
- stage: Builds
  displayName: 'Publish IaC Artifacts'
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        sourceFolder: 'azure-pipelines/templates'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: $(artifactName)

- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  jobs:
  - template: templates/template-iac-logicapp.yml
    parameters:
      environment: $(devEnvironment)
      serviceConnection: 'AZD-EST-SND1'

- stage: TEST
  displayName: 'TEST Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  jobs:
  - template: templates/template-iac-logicapp.yml
    parameters:
      environment: $(testEnvironment)
      serviceConnection: 'AZD-EST-SND1'
