# Azure pipeline to deploy a Logic App's (Standard) structure to one or more environments
# This pipeline deploys the structure (including service plan, storage account and connections).
# The Logic App workflows are deployed separately using the cd-pipeline.yml pipeline.

trigger: none

pr: none

variables:
- template: variables/pipeline-vars-common.yml

resources:
  pipelines:
  - pipeline: cipipeline
    source: payment-statement-integrations-ci
    trigger:
      branches:
      - test-az-pipeline

stages:
- stage: Build
  displayName: 'Publish IaC Artifacts'
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        artifactPath='$(Pipeline.Workspace)/cipipeline/logicapp-artifact'
        unzip -q '$artifactPath/$(resources.pipeline.cipipeline.runID).zip' -d $(Pipeline.Workspace)/unpacked
      displayName: Unzip artifact
    - bash: |
        ls -al $(Pipeline.Workspace)/unpacked
      displayName: Debug1

- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars-dev.yml
  jobs:
  - template: templates/template-iac-logicapp.yml
    parameters:
      environment: ${{ variables.envShortName }}
      serviceConnection: ${{ variables.serviceConnection }}

- stage: TEST
  displayName: 'TEST Deployment'
  variables:
  - template: variables/pipeline-vars-test.yml
  jobs:
  - template: templates/template-iac-logicapp.yml
    parameters:
      environment: ${{ variables.envShortName }}
      serviceConnection: ${{ variables.serviceConnection }}
